# auth_portal_app/.streamlit/settings.toml
# ==========================================
# プロジェクト名：auth_portal_app
# ==========================================

# -------------------------------
# アクセスレベル設定
# -------------------------------

# ログイン不要（公開アプリ）
[access.public]
apps = [
]

# ログイン必須（一般ユーザー）
[access.user]
apps = [
    "bot",              # RAGチャットボット
    "minutes",          # 議事録生成アプリ
    "text_studio",      # 文書校正アプリ
    "image_maker"       # 画像生成アプリ
]

# 許可された人のみ（restricted）
[access.restricted]
apps = [
    "login_test",       # 特定ユーザーにのみ許可
    "slide_viewer",

]

# 管理者のみ
[access.admin]
apps = [
    "command_station",  # サーバー制御・Nginx操作
    "doc_manager",      # PDF整理・OCR
    "auth_portal",      # 認証管理そのもの
]

# -------------------------------
# 管理者ユーザー（ログイン名を列挙）
# -------------------------------
[admin_users]
users = ["maeda", "admin", "t-okamoto", "y-maeda"]

# -------------------------------
# 制限アプリ（restricted）の許可ユーザー
# -------------------------------
[restricted_users]
login_test = ["maeda", "y-maeda", "admin"]


# 以下は不要
# -----------------------------------------
# インボックスのファイルの保存先（location 別）
# -----------------------------------------
# インボックスのファイルの保存先（将来切替したい瞬間に mode="external" に変える）
[inbox.storage]
# "internal" または "external"
#mode = "internal"  
# mode = "external"   

[inbox.storage.Home]
#root = "/Volumes/Extreme SSD/InBoxStorages"

[inbox.storage.Prec]
#root = "/Volumes/PrecSSD/InBoxStorages"
